var s = '[{"id":1,"name":"Test1"},{"id":2,"name":"Test2"}]';
var myObject = eval("(" + s + ")");

console.log(myObject);

var s2 =
  '[{"CustomerId":1,"FirstName":"Luís"},{"CustomerId":2,"FirstName":"Leonie"},{"CustomerId":3,"FirstName":"François"},{"CustomerId":4,"FirstName":"Bjørn"},{"CustomerId":5,"FirstName":"František"},{"CustomerId":6,"FirstName":"Helena"},{"CustomerId":7,"FirstName":"Astrid"},{"CustomerId":8,"FirstName":"Daan"},{"CustomerId":9,"FirstName":"Kara"},{"CustomerId":10,"FirstName":"Eduardo"},{"CustomerId":11,"FirstName":"Alexandre"},{"CustomerId":12,"FirstName":"Roberto"},{"CustomerId":13,"FirstName":"Fernanda"},{"CustomerId":14,"FirstName":"Mark"},{"CustomerId":15,"FirstName":"Jennifer"},{"CustomerId":16,"FirstName":"Frank"},{"CustomerId":17,"FirstName":"Jack"},{"CustomerId":18,"FirstName":"Michelle"},{"CustomerId":19,"FirstName":"Tim"},{"CustomerId":20,"FirstName":"Dan"},{"CustomerId":21,"FirstName":"Kathy"},{"CustomerId":22,"FirstName":"Heather"},{"CustomerId":23,"FirstName":"John"},{"CustomerId":24,"FirstName":"Frank"},{"CustomerId":25,"FirstName":"Victor"},{"CustomerId":26,"FirstName":"Richard"},{"CustomerId":27,"FirstName":"Patrick"},{"CustomerId":28,"FirstName":"Julia"},{"CustomerId":29,"FirstName":"Robert"},{"CustomerId":30,"FirstName":"Edward"},{"CustomerId":31,"FirstName":"Martha"},{"CustomerId":32,"FirstName":"Aaron"},{"CustomerId":33,"FirstName":"Ellie"},{"CustomerId":34,"FirstName":"João"},{"CustomerId":35,"FirstName":"Madalena"},{"CustomerId":36,"FirstName":"Hannah"},{"CustomerId":37,"FirstName":"Fynn"},{"CustomerId":38,"FirstName":"Niklas"},{"CustomerId":39,"FirstName":"Camille"},{"CustomerId":40,"FirstName":"Dominique"},{"CustomerId":41,"FirstName":"Marc"},{"CustomerId":42,"FirstName":"Wyatt"},{"CustomerId":43,"FirstName":"Isabelle"},{"CustomerId":44,"FirstName":"Terhi"},{"CustomerId":45,"FirstName":"Ladislav"},{"CustomerId":46,"FirstName":"Hugh"},{"CustomerId":47,"FirstName":"Lucas"},{"CustomerId":48,"FirstName":"Johannes"},{"CustomerId":49,"FirstName":"Stanisław"},{"CustomerId":50,"FirstName":"Enrique"},{"CustomerId":51,"FirstName":"Joakim"},{"CustomerId":52,"FirstName":"Emma"},{"CustomerId":53,"FirstName":"Phil"},{"CustomerId":54,"FirstName":"Steve"},{"CustomerId":55,"FirstName":"Mark"},{"CustomerId":56,"FirstName":"Diego"},{"CustomerId":57,"FirstName":"Luis"},{"CustomerId":58,"FirstName":"Manoj"},{"CustomerId":59,"FirstName":"Puja"}]';

var myObject2 = eval("(" + s2 + ")");

console.log(myObject2);
